FROM metric-metadata-service-base-image:latest as development

# Install additional tools or dependencies for development

RUN poetry install --with development

COPY ../scripts/init_database.sh init_database.sh

EXPOSE 8080

CMD [ "bash", "-c", "./startup.sh" ]
