apiVersion: batch/v1
kind: Job
metadata:
  name: metric-metadata-service-migrations-2024-08-06-b68ae28
  namespace: production
spec:
  template:
    metadata:
      annotations:
        # disable istio on the pod due to this issue:
        # https://github.com/istio/istio/issues/11659
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: metric-metadata-service-account
      containers:
        - name: metric-metadata-service-migrations
          image: 380207309407.dkr.ecr.eu-central-1.amazonaws.com/core_services/metric-metadata-service:2024-08-06-b68ae28
          command: ["poetry"]
          args: ["run", "alembic", "upgrade", "head"]
          imagePullPolicy: "Always"
          env:
            - name: INSTANCE_NAME
              value: migration
          envFrom:
            - secretRef:
                name: metric-metadata-service-secrets
            - configMapRef:
                name: metric-metadata-service-config
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 7200 # delete the job 2 hours after finished
  parallelism: 1
