apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: production
  name: metric-metadata-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metric-metadata-service
  minReplicas: 1
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60
