"""Removed timestamp as property of event

Revision ID: 65f5c048833b
Revises: 38737c2e1f07
Create Date: 2024-11-14 17:59:03.238130

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "65f5c048833b"
down_revision: Union[str, None] = "38737c2e1f07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "timestamp")
    op.execute("ALTER TYPE entitytypeenum RENAME ATTRIBUTE METRIC_HIERARCHY TO METRIC_SET_TREE")
    op.execute("ALTER TYPE entitytypeenum RENAME ATTRIBUTE METRIC_DATA TO DATA_METRIC")
    op.execute("ALTER TYPE entitytypeenum ADD VALUE PROPERTY")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False)
    )

    op.execute("ALTER TYPE entitytypeenum RENAME ATTRIBUTE METRIC_SET_TREE TO METRIC_HIERARCHY")
    op.execute("ALTER TYPE entitytypeenum RENAME ATTRIBUTE DATA_METRIC TO METRIC_DATA")
    # ### end Alembic commands ###
