"""Small adjustments to entities and indexing

Revision ID: 7f4aa96b8c93
Revises: 130dfde97207
Create Date: 2024-11-09 10:16:36.963791

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7f4aa96b8c93"
down_revision: Union[str, None] = "130dfde97207"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_organizations_organization_email", table_name="organizations")
    op.drop_index("ix_organizations_organization_name", table_name="organizations")
    op.drop_table("organizations")
    op.create_index(op.f("ix_data_metrics_metric_type"), "data_metrics", ["metric_type"], unique=False)
    op.create_index(op.f("ix_data_metrics_name"), "data_metrics", ["name"], unique=False)
    op.alter_column("events", "user_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(op.f("ix_events_node_id"), "events", ["node_id"], unique=False)
    op.create_index(op.f("ix_events_node_type"), "events", ["node_type"], unique=False)
    op.alter_column("metric_set_trees", "node_name", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column("metric_set_trees", "node_reference_id", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.drop_constraint("metric_sets_ms_id_key", "metric_sets", type_="unique")
    op.drop_column("metric_sets", "ms_id")
    op.create_index("ix_metric_metric_set_id_status", "metrics", ["metric_set_id", "status"], unique=False)
    op.create_index(op.f("ix_metrics_metric_set_id"), "metrics", ["metric_set_id"], unique=False)
    op.drop_index("ix_properties_property_description", table_name="properties")
    op.drop_index("ix_properties_property_name", table_name="properties")
    op.create_index(op.f("ix_properties_property_name"), "properties", ["property_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_property_name"), table_name="properties")
    op.create_index("ix_properties_property_name", "properties", ["property_name"], unique=True)
    op.create_index("ix_properties_property_description", "properties", ["property_description"], unique=True)
    op.drop_index(op.f("ix_metrics_metric_set_id"), table_name="metrics")
    op.drop_index("ix_metric_metric_set_id_status", table_name="metrics")
    op.add_column("metric_sets", sa.Column("ms_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint("metric_sets_ms_id_key", "metric_sets", ["ms_id"])
    op.alter_column("metric_set_trees", "node_reference_id", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column("metric_set_trees", "node_name", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.drop_index(op.f("ix_events_node_type"), table_name="events")
    op.drop_index(op.f("ix_events_node_id"), table_name="events")
    op.alter_column("events", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("ix_data_metrics_name"), table_name="data_metrics")
    op.drop_index(op.f("ix_data_metrics_metric_type"), table_name="data_metrics")
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("organization_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("organization_email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("last_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("deleted", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="organizations_pkey"),
    )
    op.create_index("ix_organizations_organization_name", "organizations", ["organization_name"], unique=True)
    op.create_index("ix_organizations_organization_email", "organizations", ["organization_email"], unique=True)
    # ### end Alembic commands ###
