"""Adding missing properties and indexes

Revision ID: 889825a1f483
Revises: a3a616630bbc
Create Date: 2024-11-09 10:43:04.783080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889825a1f483'
down_revision: Union[str, None] = 'a3a616630bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_metrics', sa.Column('data_id', sa.UUID(), nullable=False, comment='Field used to store the UUID to the data nodes which are updated every quarter.'))
    op.create_index(op.f('ix_data_metrics_data_id'), 'data_metrics', ['data_id'], unique=False)
    op.create_index(op.f('ix_metrics_data_metric_id'), 'metrics', ['data_metric_id'], unique=False)
    op.create_index(op.f('ix_metrics_parent_metric_id'), 'metrics', ['parent_metric_id'], unique=False)
    op.create_index(op.f('ix_metrics_parent_section_id'), 'metrics', ['parent_section_id'], unique=False)
    op.drop_constraint('metrics_data_metric_id_fkey', 'metrics', type_='foreignkey')
    op.create_foreign_key(None, 'metrics', 'data_metrics', ['data_metric_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.create_foreign_key('metrics_data_metric_id_fkey', 'metrics', 'metric_set_trees', ['data_metric_id'], ['id'])
    op.drop_index(op.f('ix_metrics_parent_section_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_parent_metric_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_data_metric_id'), table_name='metrics')
    op.drop_index(op.f('ix_data_metrics_data_id'), table_name='data_metrics')
    op.drop_column('data_metrics', 'data_id')
    # ### end Alembic commands ###
