apiVersion: batch/v1
kind: Job
metadata:
  name: metric-metadata-service-migrations-2024-12-19-d92d44b
  namespace: development
spec:
  template:
    metadata:
      annotations:
        # disable istio on the pod due to this issue:
        # https://github.com/istio/istio/issues/11659
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: metric-metadata-service-account
      containers:
        - name: metric-metadata-service-migrations
          image: 761124675977.dkr.ecr.eu-central-1.amazonaws.com/core_services/metric-metadata-service:2024-12-19-d92d44b
          command: ["poetry"]
          args: ["run", "alembic", "upgrade", "head"]
          imagePullPolicy: "Always"
          env:
            - name: INSTANCE_NAME
              value: migration
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: metric-metadata-app
                  key: uri
          envFrom:
            - secretRef:
                name: metric-metadata-app
            - secretRef:
                name: metric-metadata-redis-password
            - configMapRef:
                name: metric-metadata-service-config

      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 7200 # delete the job 2 hours after finished
  parallelism: 1
